---
- name: Gather sunxi facts
  hosts: sunxi
  become: yes
  gather_facts: False
  roles:
  - sunxi-facts
  tags:
  - always

- name: Deploy u-boot
  hosts: sunxi
  become: yes
  gather_facts: False
  roles:
  - sunxi-uboot
  tags:
  - sunxi
  - uboot

- name: Install sunxi kernel
  hosts: sunxi
  become: yes
  gather_facts: False
  roles:
  - sunxi-kernel
  tags:
  - sunxi
  - kernel

- name: Apply sunxi boot config
  hosts: sunxi
  become: yes
  gather_facts: False
  roles:
  - sunxi-boot
  tags:
  - sunxi
  - boot

- name: Apply devboard config
  hosts: devboard
  become: yes
  gather_facts: False
  roles:
  - ser2net
  - gpio-reboot
  tags:
  - sunxi
  - dev
...
