---
- hosts: vms
  become: yes
  roles:
  - os/debian-defaults
  - role: os/upgraded
    tags:
    - upgrade
  - os/default-packages
  - os/remote-syslog
  - os/serial-terminal
  - os/sshkeys
  - os/pve-guest
...
