---
- name: Install tools
  package:
    name: "{{ item }}"
    state: latest
  with_items:
  - ser2net
- name: ser2net configfile
  template:
    src: ser2net.conf
    dest: /etc/ser2net.conf
  notify:
  - restart ser2net
...
