---
spotifyd_path: /usr/local/bin
spotifyd_version: 0.2.11
spotifyd_release_date: 2019-06-19
spotifyd_version_string: 'spotifyd version {{ spotifyd_version }}'
spotifyd_release_x86_64: 'https://github.com/Spotifyd/spotifyd/releases/download/{{ spotifyd_version }}/spotifyd-{{ spotifyd_release_date }}-x86.zip'
spotifyd_release_arm: 'https://github.com/Spotifyd/spotifyd/releases/download/{{ spotifyd_version }}/spotifyd-{{ spotifyd_release_date }}-armv6.zip'
...
