---
- name: Install required packages
  apt: name={{ item}} state=present
  with_items:
  - monitoring-plugins
  - icinga2
- name: enable API
  icinga2_feature:
    name: api
    state: present
- name: Get PKI ticket
  icinga2_pki:
    action: ticket
    common_name: "{{ ansible_fqdn }}"
  register: icinga
  delegate_to: "{{ icinga2_master_fqdn }}"
- name: Create temporary self-signed certificate
  icinga2_pki:
    action: new-cert
    common_name: "{{ ansible_fqdn }}"
    creates: "/etc/icinga2/pki/{{ ansible_fqdn }}.crt"
- name: Save trusted master certificate
  icinga2_pki:
    action: save-cert
    master_host: "{{ icinga2_master_fqdn }}"
    common_name: "{{ ansible_fqdn }}"
    creates: "/etc/icinga2/pki/trusted-master.crt"
- name: request signed certificate from master using ticket
  icinga2_pki:
    action: request
    master_host: "{{ icinga2_master_fqdn }}"
    ticket: "{{ icinga.ticket }}"
    common_name: "{{ ansible_fqdn }}"
    creates: "/etc/icinga2/pki/{{ ansible_fqdn }}.crt"
    ca_file: "/etc/icinga2/pki/ca.crt"
- name: create Icinga config files
  template:
    src: "{{ item }}.conf"
    dest: "/etc/icinga2/{{ item }}.conf"
  with_items:
  - zones
  - constants
  notify:
  - restart icinga2
