---
- name: Add dtc repository
  apt_repository:
    repo: ppa:jorik-kippendief/dtc
    filename: jorik-kippendief-dtc
    state: present
- name: Install packages
  package:
    name: "{{ item }}"
    state: latest
  with_items:
    - u-boot-tools
    - make
    - device-tree-compiler
- name: Userspace U-Boot environment config
  template:
    src: fw_env.config
    dest: /etc/fw_env.config
...
