---
- name: Install Makefile for U-boot scripts
  template:
    src: Makefile
    dest: /boot/Makefile
  notify:
  - recompile uboot scripts
- name: Install U-boot scripts
  template:
    src: "{{ item }}.cmd"
    dest: "/boot/{{ item }}.cmd"
  with_items:
    - boot
  register: scripts
  notify:
  - recompile uboot scripts
- name: Install U-boot boot.txt
  template:
    src: boot.txt
    dest: "/boot/boot.txt"
- name: Install FDT overlays
  copy:
    src: "{{ item }}.dtso"
    dest: /boot/{{ item }}.dtso
  with_items: "{{ sunxi_overlays }}"
  notify:
  - recompile uboot scripts
...
